name: Crowdin merge

on:
  workflow_dispatch:

jobs:
  merge:
    name: Squash merge Crowdin into Dev
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout dev branch
      - name: Checkout dev
        uses: actions/checkout@v5
        with:
          ref: dev
          fetch-depth: 0
          clean: true

      # Step 2: Fetch the latest crowdin branch
      - name: Fetch crowdin branch
        run: git fetch origin crowdin

      # Step 3: Squash merge crowdin into dev
      - name: Squash merge crowdin into dev
        run: |
          git config --local user.name "Crowdin Bot"
          git config --local user.email "support+bot@crowdin.com"
          git merge --squash origin/crowdin
          git commit --allow-empty -m "chore: Update translations from Crowdin"
          git push origin dev
